### ISSUE TITLE
Constantly check if a job running and if not redeploying it

### ISSUE THREAD

**Issue by stephen-lazarionok** [ing-bank/flink-deployer#25]
The problem is that if a Flink job manager dies then a job might be not started again. So, I think it will be useful to have a functionality that will check whether a job is running on a regular basis and if not then re-deploy the job(s).

**Comment by nielsdenissen** [comment]
Hi Stephen, we didn't incorporate this into our deployer, since this scenario is solved within Flink itself by using a zookeeper cluster to maintain the state of a cluster: https://ci.apache.org/projects/flink/flink-docs-release-1.7/ops/jobmanager_high_availability.html.

**Comment by stephen-lazarionok** [comment]
hm... but by having this functionality in flink-deployer it's possible to considerably simplify the deployment.
