### ISSUE TITLE
Any plan for supporting other commands?

### ISSUE THREAD

**Issue by hustclf** [ing-bank/flink-deployer#26]
flink cli also provide commands such as 

- Cancel a job:

`./bin/flink cancel <jobID>`

- Cancel a job with a savepoint:

`./bin/flink cancel -s [targetDirectory] <jobID>`

- Stop a job (streaming jobs only):

`./bin/flink stop <jobID>`

Is therer any plan to rich supported commands?

**Comment by nielsdenissen** [comment]
Hi hustclf, there are currently no plans to support this on our side. Since we're using the deployer in our CI, normally our only use-case is to do automated deployments/updates. But I can image it can be useful for others certainly, so feel free to add it!

**Comment by hustclf** [comment]
Thanks for your reply!  I also using deployer for automate deploying our flink jobs on kubernetes, and it is convenient .  I will try to contribute new feature for flink deployer in the future, maybe It is a good chance to exercise golang :) .
