### ISSUE TITLE
Using flink deployer to manage more than one job doesn't work

### ISSUE THREAD

**Issue by joshuavijay** [ing-bank/flink-deployer#28]
In update_job.go the filterRunningJobs function only filters based on RUNNING status (just like the function name claims) but I believe we need it to also filter based on JobNameBase. It does not work when I have two jobs deployed in my flink cluster and try to update one of them. The filter function returns 2 RUNNING and always ends up in an error "job name with base "X" has 2 instances running. Aborting update", though there is only one job with name X running. I've fixed it in my local by filtering based on both job status and base name.
If you confirm this to be an issue (wondering if I am missing something), I can create a pull request with the fix.
Thanks.

**Comment by mrooding** [comment]
Hi @joshuavijay 

I've just verified it locally. You're completely right that we neglected to include the job base name in the filtering. I guess it worked out for most people since it's quite common to run a cluster per job.

If you have the fix locally, please open a PR to save me some time from fixing it myself

**Comment by joshuavijay** [comment]
Can you give me permission to push to this repo? I tried to push my local branch to remote, but fails.

pc1:~/go/src/github.com/ing-bank/flink-deployer$ git push --set-upstream origin feature/support_multi_job
Username for 'https://github.com': joshuavijay
Password for 'https://joshuavijay@github.com': 
remote: Permission to ing-bank/flink-deployer.git denied to joshuavijay.
fatal: unable to access 'https://github.com/ing-bank/flink-deployer/': The requested URL returned error: 403

**Comment by joshuavijay** [comment]
Hi @mrooding 
Would you mind taking a quick look at my pull request. 

Thanks

**Comment by mrooding** [comment]
I've left some comments

**Comment by joshuavijay** [comment]
Thanks for the comments. I've addressed them all. Please take a minute to review.

**Comment by mrooding** [comment]
Resolved by release 1.1.2
