### ISSUE TITLE
Questions about local development

### ISSUE THREAD

**Issue by hustclf** [ing-bank/flink-deployer#33]
Hi, I am a newbie for golang, and trying to contribute new features for flink deployers.

What trouble me mosts is that all the dependencies for flink deployers has been included inside  the project itself,  why we still import the dependency using `github.com/ing-bank/flink-deployer/cmd/cli/flink` instead of `flink-deployer/cmd/cli/flink` ?

When I want to add new file to the dependencies, I have to change a lot of code about import to make it run as I expected.

Looking forward to your reply.

**Comment by mrooding** [comment]
Hi

First of all, thank you for wanting to contribute.

Checking in the `vendor/` folder is actually common in Golang projects. We use [dep](https://golang.github.io/dep/) to manage our dependencies. 

There's an [article](https://blog.gopheracademy.com/advent-2017/managing-dependencies-forks-and-code-patches-with-dep/) describing the problem you're facing (among others) and it also offers a solution which includes changing the `Gopkg.toml` file in the project. 

I hope this solves your problem. Feel free to add the solution to the README.md if you plan on contributing.

**Comment by hustclf** [comment]
Thanks!  the article is exactly what I need.
