### ISSUE TITLE
Update job functionality not suitable for automation

### ISSUE THREAD

**Issue by joshuavijay** [ing-bank/flink-deployer#34]
We have 5 Flink clusters with 8 to 10 nodes in each cluster. I am using this project to automate our deployments/upgrades through Ansible. The last Ansible task in my playbook is to deploy the job in those clusters after installing and configuring Flink. In our staging systems some times when we hit a bug where a job crashes, I found it annoying when I had to manually run a flink-deployer deploy. I found it would be useful to run our Ansible play again with the new job (jar file) with fixes. However the update would fail because there is no instance of running job. There are two ways I could have gone about it:
1. Write more Ansible tasks that fetches running jobs over rest API and then decides if it should run update or deploy (repeat the first part of update functionality of update-deployer)
2. Change flink-deployer update function to continue with the deployment when there are no instances of job running instead of failing. The advantage to this approach is my Ansible task can  always run the update command without having to implement a decision tree. Also engineers, test automation scripts and our continuous delivery system can use one command to deploy/re-deploy a job instead of implementing a decision tree everywhere.

Due to the advantages of Option 2 I explained above  and also it was quicker to do that change and I went with #2. I am not sure what is your opinion on this and if I should contribute that change back to this project. My implementation is straightforward and simple. But we can have both functionalities of update with a --fail-on-no-jobs flag. Let me know.

Thanks.

**Comment by mrooding** [comment]
Hi Joshua

As discussed in the other issue already, I'd prefer to have a flag on the update command `--fallback-to-deploy` that does a deploy of the job if no running instance is found. The default update behaviour would still be to cancel if the job is not available, but you're able to configure it to act differently if that's what you want.

What do you think about this?

**Comment by joshuavijay** [comment]
Yes. Exactly as you described.

I've done a quick hack in my own fork. I've changed the update function to continue to deploy if there is no job running. I'm busy with a product release now. I will have time later after the release do a proper fix with --fallback-to-deploy flag and contribute back, if you haven't got to it by then.

Thanks

**Comment by Wosin** [comment]
Hey @mrooding,
what's the status on this ??

**Comment by mrooding** [comment]
Hi @Wosin 

I haven't been working on this feature. Maybe @joshuavijay has had time to work on it?

**Comment by joshuavijay** [comment]
@Wosin @mrooding  
Apologize for the delay. I've created a PR now.

**Comment by joshuavijay** [comment]
The issue has been addressed with a --fbd flag.
